CREATE TABLE bankers(
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255),
   username VARCHAR(255),
   password VARCHAR(255),
   login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   logout_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);